source 'https://rubygems.org'

gem 'rails', '7.1.2'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier', '~> 4.2'
gem 'coffee-rails', '~> 5.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
gem 'bcrypt', '~> 3.1', '>= 3.1.20'
gem 'bootstrap', '~> 5.3', '>= 5.3.2'

group :development, :test do
  gem 'byebug', '~> 11.1', '>= 11.1.3', platform: :mri
  gem 'pry', '~> 0.14.2'
  gem 'rspec-rails', '~> 6.1'
  gem 'capybara', '~> 3.39', '>= 3.39.2'
  gem 'database_cleaner', '~> 2.0', '>= 2.0.2'
  gem 'rack_session_access', '~> 0.2.0'
  gem 'rubocop', '~> 1.59'
end

group :development do
  gem 'web-console', '~> 4.2', '>= 4.2.1'
  gem 'listen', '~> 3.8'
  gem 'spring', '~> 4.1', '>= 4.1.3'
  gem 'spring-watcher-listen', '~> 2.1'
end
