source 'https://rubygems.org'

gem 'rails', '7.1.2'
gem 'sqlite3'
gem 'puma', '~> 6.4'
gem 'sass-rails'
gem 'sassc-rails'
gem 'uglifier', '~> 4.2'
gem 'coffee-rails', '~> 5.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.11', '>= 2.11.5'

group :development, :test do
  gem 'byebug', '~> 11.1', '>= 11.1.3', platform: :mri
  gem 'pry', '~> 0.14.2'
  gem 'rspec-rails', '~> 6.1'
  gem 'capybara', '~> 2.7', '>= 2.7.1'
  gem 'database_cleaner', '~> 2.0', '>= 2.0.2'
  gem 'rubocop', '~> 1.59'
end

group :development do
  gem 'web-console', '~> 4.2', '>= 4.2.1'
  gem 'listen', '~> 3.8'
  gem 'spring', '~> 4.1', '>= 4.1.3'
  gem 'spring-watcher-listen', '~> 2.1'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
