source 'https://rubygems.org'

ruby '3.3.0'

gem 'rails', '7.1.2'
# TODO: Move sqlite gem to the development group
gem 'sqlite3'
gem 'puma', '3.10.0'
gem 'sass-rails'
gem 'uglifier', '~> 4.2'
gem 'coffee-rails', '~> 5.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
gem 'rspotify', '~> 2.6'
gem 'bootstrap', '~> 5.3', '>= 5.3.2'

# TODO: Add a production group and add the pg gem

group :development, :test do
  gem 'dotenv-rails', '~> 2.8', '>= 2.8.1'
  gem 'byebug', '~> 11.1', '>= 11.1.3', platform: :mri
  gem 'pry', '~> 0.14.2'
  gem 'rspec-rails', '~> 6.1'
  gem 'capybara', '~> 3.39', '>= 3.39.2'
  gem 'database_cleaner', '~> 2.0', '>= 2.0.2'
  gem 'rubocop', '~> 1.59'
  gem 'webmock', '~> 3.19', '>= 3.19.1'
end

group :development do
  gem 'web-console', '~> 4.2', '>= 4.2.1'
  gem 'listen', '~> 3.8'
  gem 'spring', '~> 4.1', '>= 4.1.3'
  gem 'spring-watcher-listen', '~> 2.1'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
